kind: Service
apiVersion: v1
metadata:
  name: fotoanalyzer
  labels:
    app: fotoanalyzer
spec:
  type: ClusterIP
  selector:
    app: fotoanalyzer
  ports:
    - name: tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: fotoanalyzer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fotoanalyzer
  template:
    metadata:
      labels:
        app: fotoanalyzer
        version: v1
    spec:
      containers:
      - name: fotoanalyzer
        image: fotoanalyzer
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
